---
apiVersion: v1
kind: Namespace
metadata:
  name: minibench

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: minibench
data:
  BROKERS: "redpanda.redpanda.svc.cluster.local:9093"
  TOPIC_PREFIX: "test-"
  TOPIC_COUNT: "10"
  PARTITIONS: "1"
  REPLICATION_FACTOR: "1"
  LINGER: "1ms"
  RATE_LIMIT_MIB: "1"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minibench
  namespace: minibench
  labels:
    app: minibench
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minibench
  template:
    metadata:
      labels:
        app: minibench
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "7070"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: minibench
          image: paulmw/minibench:0.0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7070
              name: metrics
              protocol: TCP
          env:
            - name: BROKERS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BROKERS
                  optional: false
            - name: TOPIC_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: TOPIC_PREFIX
                  optional: true
            - name: TOPIC_COUNT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: TOPIC_COUNT
                  optional: true
            - name: PARTITIONS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: PARTITIONS
                  optional: true
            - name: REPLICATION_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: REPLICATION_FACTOR
                  optional: true
            - name: STATIC_RECORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: STATIC_RECORD
                  optional: true
            - name: RECORD_BYTES
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RECORD_BYTES
                  optional: true
            - name: COMPRESSION
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: COMPRESSION
                  optional: true
            - name: POOL_PRODUCE
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: POOL_PRODUCE
                  optional: true
            - name: DISABLE_IDEMPOTENCY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: DISABLE_IDEMPOTENCY
                  optional: true
            - name: MAX_INFLIGHT_PRODUCE_PER_BROKER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: MAX_INFLIGHT_PRODUCER_PER_BROKER
                  optional: true
            - name: ACKS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: ACKS
                  optional: true
            - name: LINGER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: LINGER
                  optional: true
            - name: BATCH_MAX_BYTES
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BATCH_MAX_BYTES
                  optional: true
            - name: BATCH_RECS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: BATCH_RECS
                  optional: true
            - name: SYNC
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SYNC
                  optional: true
            - name: CONCURRENCY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CONCURRENCY
                  optional: true
            - name: RATE_LIMIT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RATE_LIMIT
                  optional: true
            - name: RATE_LIMIT_MIB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: RATE_LIMIT_MIB
                  optional: true
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: LOG_LEVEL
                  optional: true
            - name: TLS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: TLS
                  optional: true
            - name: CA_CERT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CA_CERT
                  optional: true
            - name: CLIENT_CERT
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CLIENT_CERT
                  optional: true
            - name: CLIENT_KEY
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: CLIENT_KEY
                  optional: true
            - name: SASL_METHOD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SASL_METHOD
                  optional: true
            - name: SASL_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SASL_USER
                  optional: true
            - name: SASL_PASS
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: SASL_PASS
                  optional: true
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"
            limits:
              memory: "64Mi"
              cpu: "100m"
          livenessProbe:
            httpGet:
              path: /metrics
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /metrics
              port: 7070
            initialDelaySeconds: 3
            periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: minibench
  namespace: minibench
  labels:
    app: minibench
spec:
  type: ClusterIP
  selector:
    app: minibench
  ports:
    - port: 7070
      targetPort: 7070
      protocol: TCP
      name: metrics